#!/bin/bash

read -p "Kasutaja: " user
read -sp "Parool: " password
read -p "Sisestage gruppi nimi(tühi = ilam grupita):" group

sudo useradd -m -s /bin/bash $user
echo "$user:$password" | sudo chpasswd
if [ -z $group ]; then
  sudo usermod -a -G kylaline $user
else
sudo groupadd $group
sudo usermod -a -G $group $user
fi
echo "User '$user' has been created with the password '$password'"
sudo mkdir /home/$user/kaust
sudo touch /home/$user/kaust/teretulemast_$user.txt

