#!/bin/bash

function varunda() {
	date=$(date +%Y-%m-%d_%H-%M)
	faili_nimi_laiendiga=$(basename $1)
	faili_nimi=${faili_nimi_laiendiga%%.*}
	laiendi=${faili_nimi_laiendiga##*.}
	touch /home/melmers/backup/"$faili_nimi"_"$date"."$laiendi"
	cp $1 /home/melmers/backup/"$faili_nimi"_"$date"."$laiendi"
}
read -p "millist faili soovite backup-ida(täielik asukoht): " backup
varunda $backup
